### PR TITLE
Fixing esp_secure_cert_get_ca_cert certificate offset bug

### PR DESCRIPTION
**Pull request by mohabdallah**

### CODE REVIEW

**Comment by AdityaHPatwardhan** [comment]
@mohabdallah Can you please update your commit message and add following line at the end (without quotes)
``` Closes https://github.com/espressif/esp_secure_cert_mgr/issues/12``` 

Also please sign the necessary Contributor License Agreement

**Comment by mohabdallah** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mohabdallah** [comment]
@AdityaHPatwardhan Done

**Comment by AdityaHPatwardhan** [comment]
I think you merged a different branch into this one, that has messed up the commit history.
Can you please do one last thing and squash the commits.
Sorry for troubling you and thanks for your patience.
I can do it at my end but that would cause a problem with showing your contribution.
Thanks,
Aditya

**Comment by mohabdallah** [comment]
@AdityaHPatwardhan I think I will repeat the process again and add the needed line from the start in a new pull request

**Comment by AdityaHPatwardhan** [comment]
Oh Okay,
that also works.

Please remember to add ```Closes https://github.com/espressif/esp_secure_cert_mgr/issues/12``` to your commit message.
Thanks

**Pull request closed without merging**
