### PR TITLE
allow flashing when flash encryption is enabled (and bootloader encryption enabled)

### PR DESCRIPTION
**Pull request by danielb-IDG**
Detects if flash is encrypted (via e-fuse) and attempt to flash partition via the booloader.
This will only work in development mode when uart bootloader is enabled and is able to transparently encrypt partition data

requires following kconfig options to be enabled
CONFIG_SECURE_FLASH_ENC_ENABLED
CONFIG_SECURE_FLASH_ENCRYPTION_MODE_DEVELOPMENT
CONFIG_SECURE_FLASH_UART_BOOTLOADER_ALLOW_ENC

CONFIG_SECURE_INSECURE_ALLOW_DL_MODE or CONFIG_SECURE_ENABLE_SECURE_ROM_DL_MODE

### CODE REVIEW

**Comment by AdityaHPatwardhan** [comment]
Hi @danielb-IDG 
Thanks for your PR.
Can you add more details about the issue that you faced which is fixed by this PR?
Currently if you just generate the `esp_secure_cert.bin` without flashing it ( by providing the `--skip_flash`) option then it shall generate a partition locally.
Which can be flashed with executing an esptool command with providing respective flags.

**Comment by danielb-IDG** [comment]
There was no issue or bug. It is definitely possible to use --skip-flash, I just added it as an extra convenience for the user if they have a mix of boards that have encryption enabled on some and some not encrypted. It automatically detects whether the board is using encryption and encrypts the partition if it is enabled.

**Comment by AdityaHPatwardhan** [comment]
@danielb-IDG I see, thanks for your explanation.
Actually, though I agree that changes add a bit of convenience for the user who has flash encryption enabled in development mode. I think it also adds additional complexity in the tool itself. I am currently trying to weigh the added complexity and the functionality that it adds.

For e.g., I have following concerns.
1) While we check here if `SPI_BOOT_CRYPT_CNT` is disabled or not, it is actually also important to check here if `DIS_DOWNLOAD_MANUAL_ENCRYPT` is disabled or not because technically that is the only way the `--encrypt` operation shall succeed.
2) As it happens the name of the eFuse is different for `esp32` target where it is named as `FLASH_CRYPT_CNT` and the other eFuse is named as `DISABLE_DL_ENCRYPT`, As we also support the esp32 target, we also need to have respective changes for esp32 as well.
3) One main concern I see here is that with the the above changes, the tools now also needs to have a knowledge (though limited) about the Flash Encryption feature, which seems outside of the scope of the tool.  I think it makes the tool unnecessarily complex.

Please feel free to add your thoughts on this as well.

**Comment by danielb-IDG** [comment]
Ah, That does complicate things. In that case it is probably more trouble than it's worth for you, 
but perhaps some documentation could be added to tell users to use `--skip-flash` +` esptool.py --no-stub --encrypt` if they are using flash encryption.

**Comment by AdityaHPatwardhan** [comment]
Yes, that can be added.
I will take this up as an issue and let you know when it is fixed.

**Comment by owen63** [comment]
I've just struck the same problem where I need to flash the esp_secure_cert partition on my device that has flash partition enabled. Additional help notes would be useful.

**Comment by AdityaHPatwardhan** [comment]
Hi @danielb-IDG @owen63, I have added required documentation through https://github.com/espressif/esp_secure_cert_mgr/commit/8dab813c6905e2468d47127d5655fa1818ca8aa7
I am closing the PR.
Thanks for your contribution.

**Pull request closed without merging**
